ZWEB-7348 Adapted to Modern UI-Router
z-open/zerv-ng-security pull request #9
Opened 2021-04-03 04:28 UTC by Jacob-Friesen

Right now there does not seem to be unit tests for this repository, so it is best to verify with the main application.

2021-04-12 13:19 UTC, etelmon requested changes

2021-04-12 13:19 UTC, etelmon commented on dist/zerv-ng-security.js
> +    $transitions.onSuccess({}, function () {
changes should have unit tests. we need to start at some point

2021-04-12 13:19 UTC, etelmon commented on src/resources/ui-state.resource.js
> +        $transitions.onSuccess({}, () => {
same here, let's start adding unit tests

2021-04-12 13:28 UTC, etelmon commented on dist/zerv-ng-security.js
> +    $transitions.onSuccess({}, function () {
The generated lib file was modified instead of the src file.

2021-04-12 13:34 UTC, etelmon requested changes

2021-04-12 13:34 UTC, etelmon commented on dist/zerv-ng-security.js
>  "use strict";
package  should be increased to "version": "0.0.5",

2021-04-12 15:53 UTC, etelmon commented
Besides the comments above, The new $transition implementation works as expected.

2021-04-12 22:25 UTC, Jacob-Friesen commented on src/resources/ui-state.resource.js
> +        $transitions.onSuccess({}, () => {
Added

2021-04-14 13:59 UTC, merged

2021-04-14 14:00 UTC, etelmon commented
Tag is not created yet for "version": "0.0.5",

2021-04-19 14:01 UTC, Jacob-Friesen commented
The tag was created here after merge: https://github.com/z-open/zerv-ng-security/releases/tag/0.0.5